# -*- coding: utf-8 -*-
"""BIG DATA INSIGHTS DASHBOARD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvOoAyu-1aJ32mSExC2rv8gyw7XkQHYu

**IMPORT LIBRARIES**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

"""**LOAD DATASET**"""

df = pd.read_csv("/content/superstore.csv", encoding="latin1")

"""**DATA UNDERSTANDING**"""

# First 5 Rows
df.head()

# Last 5 Rows
df.tail()

# Shape
print(df.shape)

# Columns
print(df.columns)

# Data Types
df.dtypes

# Dataset Information
df.info()

# Missing Values
df.isnull().sum()

# Duplicate Rows
df.duplicated().sum()

# Statistical Summary
df.describe()

"""**DATA CLEANING**"""

# Remove Duplicate Rows
df = df.drop_duplicates()

# Missing Values
df.isnull().sum()

# Fill Numerical Missing Values
num_cols = df.select_dtypes(include=['int64','float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Fill Categorical Missing Values
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Convert Date Columns
df['Order.Date'] = pd.to_datetime(df['Order.Date'])

df['Ship.Date'] = pd.to_datetime(df['Ship.Date'])

# Create New Columns

df['Month'] = df['Order.Date'].dt.month

df['Month_Name'] = df['Order.Date'].dt.month_name()

df['Day'] = df['Order.Date'].dt.day

"""**Exploratory Data Analysis (EDA)**"""

# Total Sales
print(df['Sales'].sum())

# Total Profit
print(df['Profit'].sum())

# Total Orders
print(df['Order.ID'].nunique())

# Category-wise Sales
print(df.groupby('Category')['Sales'].sum())

# Region-wise Sales
print(df.groupby('Region')['Sales'].sum())

# State-wise Sales
print(df.groupby('State')['Sales'].sum())

# City-wise Sales
print(df.groupby('City')['Sales'].sum())

# Monthly Sales
print(df.groupby('Month_Name')['Sales'].sum())

# Yearly Sales
print(df.groupby('Year')['Sales'].sum())

# Discount Analysis
print(df['Discount'].describe())

# Profit Analysis
print(df['Profit'].describe())

# Customer Analysis
print(df.groupby('Customer.Name')['Sales'].sum().sort_values(ascending=False).head(10))

"""**Data Visualization**"""

category_sales=df.groupby('Category')['Sales'].sum()

category_sales.plot(kind='bar',figsize=(8,5))

plt.title("Category Wise Sales")

plt.show()

monthly=df.groupby('Month')['Sales'].sum()

plt.figure(figsize=(10,5))

plt.plot(monthly.index,monthly.values,marker='o')

plt.title("Monthly Sales")

plt.show()

region=df.groupby('Region')['Sales'].sum()

plt.figure(figsize=(7,7))

plt.pie(region,labels=region.index,autopct='%1.1f%%')

plt.show()

plt.figure(figsize=(8,5))

plt.hist(df['Sales'],bins=30)

plt.title("Sales Distribution")

plt.show()

sns.boxplot(x=df['Profit'])

plt.show()

plt.figure(figsize=(8,6))

sns.heatmap(df[['Sales','Profit','Discount','Quantity']].corr(),annot=True,cmap='coolwarm')

plt.show()

plt.figure(figsize=(8,5))

plt.scatter(df['Sales'],df['Profit'])

plt.xlabel("Sales")

plt.ylabel("Profit")

plt.show()

year=df.groupby('Year')['Sales'].sum()

plt.figure(figsize=(10,5))

plt.fill_between(year.index,year.values)

plt.plot(year.index,year.values)

plt.show()

"""**Business Insights**"""

# Highest Sales Region
print(df.groupby('Region')['Sales'].sum().sort_values(ascending=False).head(1))

# Lowest Profit State
print(df.groupby('State')['Profit'].sum().sort_values().head(1))

# Best Category
print(df.groupby('Category')['Sales'].sum().sort_values(ascending=False).head(1))

# Worst Category
print(df.groupby('Category')['Sales'].sum().sort_values().head(1))

# Top 10 Customers
print(df.groupby('Customer.Name')['Sales'].sum().sort_values(ascending=False).head(10))

# Highest Discount Products
print(df.groupby('Product.Name')['Discount'].mean().sort_values(ascending=False).head(10))

# Most Profitable Segment
print(df.groupby('Segment')['Profit'].sum().sort_values(ascending=False))

"""**Export Clean Dataset**"""

df.to_csv("Cleaned_Superstore.csv",index=False)

"""# **Conclusion**

The **Big Data Insights Dashboard** project successfully analyzed the Superstore dataset using Python and data visualization techniques. The dataset was cleaned by handling missing values, removing duplicate records, and converting date columns into the appropriate format. Exploratory Data Analysis (EDA) was performed to understand sales performance, profit trends, customer behavior, regional performance, and product categories.

Several visualizations, including bar charts, line charts, pie charts, histograms, box plots, heatmaps, scatter plots, and area charts, were created to identify meaningful business patterns. The analysis revealed the highest-performing regions, best-selling categories, top customers, most profitable segments, and the impact of discounts on sales and profit.

The cleaned dataset can be further used in Power BI to create an interactive dashboard with KPI cards, charts, maps, and slicers for better business decision-making. Overall, this project demonstrates how data analytics and visualization techniques can transform raw business data into valuable insights, helping organizations improve sales performance, profitability, and strategic planning through data-driven decisions.
"""